### ISSUE TITLE
Unable to delete cluster

### ISSUE THREAD

**Issue by tombentley** [eyefloaters/console#133]
I created a Kafka cluster using invented values and clicked on "Create anyway". Obviously the resulting cluster doesn't work, but there appears to be no way to delete it. It appears in the Kafka cluster table, and I can click on it, but my only option then is to "Check the connection"

**Comment by riccardo-forina** [comment]
The whole resources/bookmark is an experiment, I'll replace it with the right layout as by Shiri's design in the following days. That said, the designs do have a "create resource" button, but we never explored the problem. Since it's not a feature required for MVP, that button will either be absent or disabled
